name: mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - pip<=24.3.1
  - pip:
      - mlflow==2.22.0
      - cloudpickle==3.1.1
      - numpy==2.0.2
      - pandas==2.2.3
      - psutil==6.0.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
